version: "3"

services:
  zeo:
    image: prabhatech/lims:v2.5.1
    command: zeo
    volumes:
      - ./data:/data

  instance1:
    image: prabhatech/lims:v2.5.1
    ports:
      - 8081:8080
    links:
      - zeo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048MB
    environment:
      ZEO_ADDRESS: "zeo:8080"

  instance2:
    image: prabhatech/lims:v2.5.1
    ports:
      - 8082:8080
    links:
      - zeo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048MB
    environment:
      ZEO_ADDRESS: "zeo:8080"

volumes:
  data:
    external: true